# Generated by Django 4.2.4 on 2023-11-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='Project_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='website_description',
            new_name='Project_status',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='website_title',
            new_name='Project_title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='date',
            new_name='dates',
        ),
    ]
